/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MacosRouteImport } from './routes/macos'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SignUpSsoCallbackRouteImport } from './routes/sign-up/sso-callback'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'
import { Route as BookRescheduleRouteImport } from './routes/book/reschedule'
import { Route as BookCancelRouteImport } from './routes/book/cancel'
import { Route as BookEventTypeSlugRouteImport } from './routes/book/$eventTypeSlug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminSchedulingRouteImport } from './routes/admin/scheduling'
import { Route as AdminResumeRouteImport } from './routes/admin/resume'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminResumeIndexRouteImport } from './routes/admin/resume.index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog.index'
import { Route as AdminResumeNewRouteImport } from './routes/admin/resume.new'
import { Route as AdminResumeProfileSlugRouteImport } from './routes/admin/resume.$profileSlug'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects.new'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin/projects.$projectId'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog.new'
import { Route as AdminBlogPostIdRouteImport } from './routes/admin/blog.$postId'
import { Route as AdminSchedulingGoogleCallbackRouteImport } from './routes/admin/scheduling/google/callback'
import { ServerRoute as ResumeExportServerRouteImport } from './routes/resume.export'

const rootServerRouteImport = createServerRootRoute()

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MacosRoute = MacosRouteImport.update({
  id: '/macos',
  path: '/macos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignUpSsoCallbackRoute = SignUpSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const BookRescheduleRoute = BookRescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => BookRoute,
} as any)
const BookCancelRoute = BookCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BookRoute,
} as any)
const BookEventTypeSlugRoute = BookEventTypeSlugRouteImport.update({
  id: '/$eventTypeSlug',
  path: '/$eventTypeSlug',
  getParentRoute: () => BookRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/$slug.lazy').then((d) => d.Route))
const AdminSchedulingRoute = AdminSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResumeRoute = AdminResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResumeIndexRoute = AdminResumeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminResumeRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminResumeNewRoute = AdminResumeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminResumeRoute,
} as any).lazy(() =>
  import('./routes/admin/resume.new.lazy').then((d) => d.Route),
)
const AdminResumeProfileSlugRoute = AdminResumeProfileSlugRouteImport.update({
  id: '/$profileSlug',
  path: '/$profileSlug',
  getParentRoute: () => AdminResumeRoute,
} as any).lazy(() =>
  import('./routes/admin/resume.$profileSlug.lazy').then((d) => d.Route),
)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin/projects.new.lazy').then((d) => d.Route),
)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin/projects.$projectId.lazy').then((d) => d.Route),
)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any).lazy(() =>
  import('./routes/admin/blog.new.lazy').then((d) => d.Route),
)
const AdminBlogPostIdRoute = AdminBlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AdminBlogRoute,
} as any).lazy(() =>
  import('./routes/admin/blog.$postId.lazy').then((d) => d.Route),
)
const AdminSchedulingGoogleCallbackRoute =
  AdminSchedulingGoogleCallbackRouteImport.update({
    id: '/google/callback',
    path: '/google/callback',
    getParentRoute: () => AdminSchedulingRoute,
  } as any)
const ResumeExportServerRoute = ResumeExportServerRouteImport.update({
  id: '/resume/export',
  path: '/resume/export',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/legacy': typeof LegacyRoute
  '/macos': typeof MacosRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/resume': typeof AdminResumeRouteWithChildren
  '/admin/scheduling': typeof AdminSchedulingRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$eventTypeSlug': typeof BookEventTypeSlugRoute
  '/book/cancel': typeof BookCancelRoute
  '/book/reschedule': typeof BookRescheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resume/$profileSlug': typeof AdminResumeProfileSlugRoute
  '/admin/resume/new': typeof AdminResumeNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/resume/': typeof AdminResumeIndexRoute
  '/admin/scheduling/google/callback': typeof AdminSchedulingGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/legacy': typeof LegacyRoute
  '/macos': typeof MacosRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/admin/scheduling': typeof AdminSchedulingRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$eventTypeSlug': typeof BookEventTypeSlugRoute
  '/book/cancel': typeof BookCancelRoute
  '/book/reschedule': typeof BookRescheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resume/$profileSlug': typeof AdminResumeProfileSlugRoute
  '/admin/resume/new': typeof AdminResumeNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/resume': typeof AdminResumeIndexRoute
  '/admin/scheduling/google/callback': typeof AdminSchedulingGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/legacy': typeof LegacyRoute
  '/macos': typeof MacosRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/resume': typeof AdminResumeRouteWithChildren
  '/admin/scheduling': typeof AdminSchedulingRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$eventTypeSlug': typeof BookEventTypeSlugRoute
  '/book/cancel': typeof BookCancelRoute
  '/book/reschedule': typeof BookRescheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resume/$profileSlug': typeof AdminResumeProfileSlugRoute
  '/admin/resume/new': typeof AdminResumeNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/resume/': typeof AdminResumeIndexRoute
  '/admin/scheduling/google/callback': typeof AdminSchedulingGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/legacy'
    | '/macos'
    | '/projects'
    | '/resume'
    | '/sign-in'
    | '/sign-up'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin/scheduling'
    | '/blog/$slug'
    | '/book/$eventTypeSlug'
    | '/book/cancel'
    | '/book/reschedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/admin/'
    | '/blog'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/resume/$profileSlug'
    | '/admin/resume/new'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/resume/'
    | '/admin/scheduling/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/legacy'
    | '/macos'
    | '/projects'
    | '/resume'
    | '/sign-in'
    | '/sign-up'
    | '/admin/scheduling'
    | '/blog/$slug'
    | '/book/$eventTypeSlug'
    | '/book/cancel'
    | '/book/reschedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/admin'
    | '/blog'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/resume/$profileSlug'
    | '/admin/resume/new'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin/scheduling/google/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/legacy'
    | '/macos'
    | '/projects'
    | '/resume'
    | '/sign-in'
    | '/sign-up'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin/scheduling'
    | '/blog/$slug'
    | '/book/$eventTypeSlug'
    | '/book/cancel'
    | '/book/reschedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/resume/$profileSlug'
    | '/admin/resume/new'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/admin/resume/'
    | '/admin/scheduling/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  LegacyRoute: typeof LegacyRoute
  MacosRoute: typeof MacosRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/resume/export': typeof ResumeExportServerRoute
}
export interface FileServerRoutesByTo {
  '/resume/export': typeof ResumeExportServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/resume/export': typeof ResumeExportServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/resume/export'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/resume/export'
  id: '__root__' | '/resume/export'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ResumeExportServerRoute: typeof ResumeExportServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macos': {
      id: '/macos'
      path: '/macos'
      fullPath: '/macos'
      preLoaderRoute: typeof MacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sign-up/sso-callback': {
      id: '/sign-up/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-up/sso-callback'
      preLoaderRoute: typeof SignUpSsoCallbackRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/book/reschedule': {
      id: '/book/reschedule'
      path: '/reschedule'
      fullPath: '/book/reschedule'
      preLoaderRoute: typeof BookRescheduleRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/cancel': {
      id: '/book/cancel'
      path: '/cancel'
      fullPath: '/book/cancel'
      preLoaderRoute: typeof BookCancelRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/$eventTypeSlug': {
      id: '/book/$eventTypeSlug'
      path: '/$eventTypeSlug'
      fullPath: '/book/$eventTypeSlug'
      preLoaderRoute: typeof BookEventTypeSlugRouteImport
      parentRoute: typeof BookRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scheduling': {
      id: '/admin/scheduling'
      path: '/scheduling'
      fullPath: '/admin/scheduling'
      preLoaderRoute: typeof AdminSchedulingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resume': {
      id: '/admin/resume'
      path: '/resume'
      fullPath: '/admin/resume'
      preLoaderRoute: typeof AdminResumeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resume/': {
      id: '/admin/resume/'
      path: '/'
      fullPath: '/admin/resume/'
      preLoaderRoute: typeof AdminResumeIndexRouteImport
      parentRoute: typeof AdminResumeRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/resume/new': {
      id: '/admin/resume/new'
      path: '/new'
      fullPath: '/admin/resume/new'
      preLoaderRoute: typeof AdminResumeNewRouteImport
      parentRoute: typeof AdminResumeRoute
    }
    '/admin/resume/$profileSlug': {
      id: '/admin/resume/$profileSlug'
      path: '/$profileSlug'
      fullPath: '/admin/resume/$profileSlug'
      preLoaderRoute: typeof AdminResumeProfileSlugRouteImport
      parentRoute: typeof AdminResumeRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$postId': {
      id: '/admin/blog/$postId'
      path: '/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AdminBlogPostIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/scheduling/google/callback': {
      id: '/admin/scheduling/google/callback'
      path: '/google/callback'
      fullPath: '/admin/scheduling/google/callback'
      preLoaderRoute: typeof AdminSchedulingGoogleCallbackRouteImport
      parentRoute: typeof AdminSchedulingRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/resume/export': {
      id: '/resume/export'
      path: '/resume/export'
      fullPath: '/resume/export'
      preLoaderRoute: typeof ResumeExportServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogPostIdRoute: typeof AdminBlogPostIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogPostIdRoute: AdminBlogPostIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminResumeRouteChildren {
  AdminResumeProfileSlugRoute: typeof AdminResumeProfileSlugRoute
  AdminResumeNewRoute: typeof AdminResumeNewRoute
  AdminResumeIndexRoute: typeof AdminResumeIndexRoute
}

const AdminResumeRouteChildren: AdminResumeRouteChildren = {
  AdminResumeProfileSlugRoute: AdminResumeProfileSlugRoute,
  AdminResumeNewRoute: AdminResumeNewRoute,
  AdminResumeIndexRoute: AdminResumeIndexRoute,
}

const AdminResumeRouteWithChildren = AdminResumeRoute._addFileChildren(
  AdminResumeRouteChildren,
)

interface AdminSchedulingRouteChildren {
  AdminSchedulingGoogleCallbackRoute: typeof AdminSchedulingGoogleCallbackRoute
}

const AdminSchedulingRouteChildren: AdminSchedulingRouteChildren = {
  AdminSchedulingGoogleCallbackRoute: AdminSchedulingGoogleCallbackRoute,
}

const AdminSchedulingRouteWithChildren = AdminSchedulingRoute._addFileChildren(
  AdminSchedulingRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminResumeRoute: typeof AdminResumeRouteWithChildren
  AdminSchedulingRoute: typeof AdminSchedulingRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminResumeRoute: AdminResumeRouteWithChildren,
  AdminSchedulingRoute: AdminSchedulingRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookRouteChildren {
  BookEventTypeSlugRoute: typeof BookEventTypeSlugRoute
  BookCancelRoute: typeof BookCancelRoute
  BookRescheduleRoute: typeof BookRescheduleRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookEventTypeSlugRoute: BookEventTypeSlugRoute,
  BookCancelRoute: BookCancelRoute,
  BookRescheduleRoute: BookRescheduleRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSsoCallbackRoute: typeof SignUpSsoCallbackRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSsoCallbackRoute: SignUpSsoCallbackRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  LegacyRoute: LegacyRoute,
  MacosRoute: MacosRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ResumeExportServerRoute: ResumeExportServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
